name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.eH1_SSH_KEY }}

      - name: Copy files to server
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ${{ secrets.eH1_SSH_SERVER }}/servers/mcrprdcts/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.eH1_SSH_KEY }}

      - name: Connect to remote server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.eH1_SSH_SERVER }} << 'EOF'

            CONTAINER_NAME=mcrprdcts01
            
            if [ $(docker ps -q -f name=$CONTAINER_NAME) ]; then
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
            fi
            cd servers/mcrprdcts
            docker build -t mcrprdcts . 
            docker run -d -e NODE_ENV=production -e PORT=3001 -e DB=${{ secrets.DB }} -p 3001:3001 --name $CONTAINER_NAME mcrprdcts
            docker system prune -f
          EOF
        env:
          DOCKER_HOST: ssh://${{ secrets.eH1_SSH_SERVER }}
