name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.eH1_SSH_KEY }}

      - name: Connect to remote server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.eH1_SSH_SERVER }} << 'EOF'
            cd /servers/mcrprdcts

            sudo docker container kill mcrprdcts01
            
            docker build -t mcrprdcts . 

            docker run -e NODE_ENV=production -e PORT=3001 -e DB=${{ secrets.DB }} -p 3001:3001 --name mcrprdcts01 mcrprdcts
          EOF
        env:
          DOCKER_HOST: ssh://${{ secrets.eH1_SSH_SERVER }}
